{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Beat Saber ML Level Generator - Master Specification\n",
    "\n",
    "**Project Goal:** Train an ML model to generate high-quality Beat Saber levels from song audio\n",
    "\n",
    "**Success Criteria:** Generate levels that 80%+ of playtesters enjoy\n",
    "\n",
    "---\n",
    "\n",
    "## Table of Contents\n",
    "1. [Project Overview](#overview)\n",
    "2. [System Architecture](#architecture)\n",
    "3. [Phase 1: MVP (Weeks 1-4)](#phase1)\n",
    "4. [Phase 2: Quality & Scorer (Weeks 5-8)](#phase2)\n",
    "5. [Phase 3: Advanced Features (Weeks 9-12)](#phase3)\n",
    "6. [Implementation Checklist](#checklist)\n",
    "7. [Evaluation Framework](#evaluation)\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Project Overview {#overview}\n",
    "\n",
    "### What We're Building\n",
    "\n",
    "**Input:** Audio file (.ogg/.egg) + difficulty level (Hard/Expert/Expert+)\n",
    "\n",
    "**Output:** Beat Saber level files (.dat format) ready to play\n",
    "\n",
    "**Approach:** Two-stage system\n",
    "- **Generator:** Transformer that maps audio → note/obstacle sequence\n",
    "- **Scorer:** Neural network that ranks map quality (added Phase 3)\n",
    "- **Pipeline:** Generate N candidates → validate constraints → rerank by score → output best\n",
    "\n",
    "### Key Design Decisions\n",
    "\n",
    "| Decision | Choice | Rationale |\n",
    "|----------|--------|----------|\n",
    "| Format support | v2 initially, v3 later | 90%+ maps are v2; simpler to start |\n",
    "| BPM changes | Parse but filter for Phase 1 | Constant BPM is easier; add variable tempo Phase 2 |\n",
    "| Lights/events | Phase 3 only | Gameplay > visuals for MVP |\n",
    "| Quality signal | Upvote ratio (75%+ with 50+ votes) | Best proxy for player enjoyment |\n",
    "| Model architecture | Token-stream Transformer | Proven for sequence generation |\n",
    "| Training approach | Positive-only → contrastive | Simple first, sophistication later |\n",
    "| Target difficulties | Hard, Expert, Expert+ | Most played; single model conditioned on difficulty |\n",
    "\n",
    "### Technology Stack\n",
    "\n",
    "- **Framework:** PyTorch 2.0+\n",
    "- **Training:** Google Colab Pro\n",
    "- **Audio:** librosa, madmom (beat tracking)\n",
    "- **Data:** BeatSaver API\n",
    "- **Storage:** ~2TB (local 1TB + cloud expansion)\n",
    "- **Python:** 3.10+ (best Colab support)\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. System Architecture {#architecture}\n",
    "\n",
    "### Data Flow\n",
    "\n",
    "```\n",
    "┌─────────────────┐\n",
    "│  BeatSaver API  │\n",
    "└────────┬────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌─────────────────────────────────────┐\n",
    "│  Download & Filter                  │\n",
    "│  - 50+ votes, 75%+ ratio            │\n",
    "│  - Constant BPM only (Phase 1)      │\n",
    "│  - v2 format priorit                │\n",
    "└────────┬────────────────────────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌─────────────────────────────────────┐\n",
    "│  Parse & Canonicalize               │\n",
    "│  - v2/v3 → unified schema           │\n",
    "│  - Beat → seconds conversion        │\n",
    "│  - Quantize to 1/16 beat grid       │\n",
    "└────────┬────────────────────────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌─────────────────────────────────────┐\n",
    "│  Feature Extraction                 │\n",
    "│  - Mel spectrogram (audio)          │\n",
    "│  - Beat/onset detection             │\n",
    "│  - Align to tick grid               │\n",
    "└────────┬────────────────────────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌─────────────────────────────────────┐\n",
    "│  Tokenize                           │\n",
    "│  - Events → discrete tokens         │\n",
    "│  - TIME_SHIFT + NOTE + OBSTACLE     │\n",
    "└────────┬────────────────────────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌─────────────────────────────────────┐\n",
    "│  Training Data                      │\n",
    "│  {audio_features, tokens, metadata} │\n",
    "└─────────────────────────────────────┘\n",
    "```\n",
    "\n",
    "### Model Components\n",
    "\n",
    "**Phase 1-2: Generator Only**\n",
    "```\n",
    "Audio Features [T, D_audio]\n",
    "     │\n",
    "     ▼\n",
    "┌──────────────────┐\n",
    "│ Transformer      │\n",
    "│ Encoder          │ ← Difficulty embedding\n",
    "│ (audio context)  │\n",
    "└────────┬─────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌──────────────────┐\n",
    "│ Transformer      │\n",
    "│ Decoder          │\n",
    "│ (autoregressive) │\n",
    "└────────┬─────────┘\n",
    "         │\n",
    "         ▼\n",
    "   Token Sequence\n",
    "         │\n",
    "         ▼\n",
    "┌──────────────────┐\n",
    "│ Constraint       │\n",
    "│ Validator        │\n",
    "└────────┬─────────┘\n",
    "         │\n",
    "         ▼\n",
    "   Valid .dat file\n",
    "```\n",
    "\n",
    "**Phase 3: Generator + Scorer**\n",
    "```\n",
    "Generate N candidates (N=16)\n",
    "     │\n",
    "     ▼\n",
    "┌──────────────────┐\n",
    "│ Validate each    │ → Reject invalid\n",
    "└────────┬─────────┘\n",
    "         │\n",
    "         ▼\n",
    "┌──────────────────┐\n",
    "│ Scorer Network   │\n",
    "│ (quality score)  │\n",
    "└────────┬─────────┘\n",
    "         │\n",
    "         ▼\n",
    "   Select best\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Phase 1: MVP (Weeks 1-4) {#phase1}\n",
    "\n",
    "### Goals\n",
    "- Download and parse Beat Saber maps\n",
    "- Build canonical data representation\n",
    "- Extract audio features\n",
    "- Train baseline generator\n",
    "- Generate playable (if rough) levels\n",
    "\n",
    "### Week 1: Data Pipeline\n",
    "\n",
    "**Deliverables:**\n",
    "1. BeatSaver downloader script\n",
    "2. v2 parser (Info.dat + difficulty .dat)\n",
    "3. Canonical schema implementation\n",
    "4. Quality filter (50+ votes, 75%+ ratio, constant BPM)\n",
    "\n",
    "**Success Criteria:**\n",
    "- Download 1000 maps for testing\n",
    "- Successfully parse 95%+ of them\n",
    "- Output canonical JSON format\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Week 1 Code Structure\n",
    "\n",
    "# TODO: Implement BeatSaver API client\n",
    "class BeatSaverAPI:\n",
    "    \"\"\"\n",
    "    Handles downloading maps from BeatSaver\n",
    "    \n",
    "    Key methods:\n",
    "    - search(filters) -> list of map IDs\n",
    "    - get_map_metadata(map_id) -> {votes, ratio, bpm, ...}\n",
    "    - download_map(map_id, output_dir)\n",
    "    \"\"\"\n",
    "    def __init__(self, api_base=\"https://api.beatsaver.com\"):\n",
    "        self.api_base = api_base\n",
    "    \n",
    "    def search(self, min_votes=50, min_ratio=0.75):\n",
    "        # TODO: Implement filtering logic\n",
    "        # See data_pipeline_spec.md for API endpoints\n",
    "        pass\n",
    "    \n",
    "    def download_map(self, map_id, output_dir):\n",
    "        # TODO: Download zip, extract to output_dir\n",
    "        pass\n",
    "\n",
    "# TODO: Implement parsers\n",
    "class BeatSaberParser:\n",
    "    \"\"\"\n",
    "    Parses v2 and v3 formats to canonical schema\n",
    "    \n",
    "    Canonical format:\n",
    "    {\n",
    "        \"metadata\": {...},\n",
    "        \"events\": [\n",
    "            {\"t_sec\": float, \"tick\": int, \"type\": str, \"data\": {...}},\n",
    "            ...\n",
    "        ]\n",
    "    }\n",
    "    \"\"\"\n",
    "    def __init__(self, ticks_per_beat=16):\n",
    "        self.ticks_per_beat = ticks_per_beat\n",
    "    \n",
    "    def parse_info_dat(self, path):\n",
    "        # TODO: Extract metadata (BPM, offset, difficulties)\n",
    "        pass\n",
    "    \n",
    "    def parse_difficulty_v2(self, path, metadata):\n",
    "        # TODO: Parse _notes, _obstacles arrays\n",
    "        # Convert beat times to seconds and ticks\n",
    "        pass\n",
    "    \n",
    "    def parse_difficulty_v3(self, path, metadata):\n",
    "        # TODO: Parse colorNotes, bombNotes, obstacles\n",
    "        # Map v3 features to v2 equivalent\n",
    "        pass\n",
    "    \n",
    "    def to_canonical(self, map_folder):\n",
    "        # TODO: Main entry point - detects version, parses, outputs canonical\n",
    "        pass\n",
    "\n",
    "# Example usage\n",
    "if __name__ == \"__main__\":\n",
    "    # Download sample maps\n",
    "    api = BeatSaverAPI()\n",
    "    map_ids = api.search(min_votes=50, min_ratio=0.75)\n",
    "    \n",
    "    for map_id in map_ids[:10]:  # Test with 10 maps\n",
    "        api.download_map(map_id, output_dir=\"data/raw\")\n",
    "    \n",
    "    # Parse to canonical format\n",
    "    parser = BeatSaberParser()\n",
    "    canonical_map = parser.to_canonical(\"data/raw/map_001\")\n",
    "    \n",
    "    print(f\"Parsed {len(canonical_map['events'])} events\")\n",
    "    print(f\"BPM: {canonical_map['metadata']['bpm']}\")\n",
    "    print(f\"Duration: {canonical_map['events'][-1]['t_sec']:.1f} seconds\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Week 2: Audio Features & Tokenization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "import librosa\n",
    "import numpy as np\n",
    "\n",
    "# TODO: Audio feature extraction\n",
    "class AudioFeatureExtractor:\n",
    "    \"\"\"\n",
    "    Extracts features aligned to tick grid\n",
    "    \n",
    "    Features per tick:\n",
    "    - Mel spectrogram (128 bins)\n",
    "    - Onset strength\n",
    "    - Beat probability\n",
    "    - Energy (bass/mid/treble)\n",
    "    \"\"\"\n",
    "    def __init__(self, sr=44100, n_mels=128, hop_length=512, context_frames=5):\n",
    "        self.sr = sr\n",
    "        self.n_mels = n_mels\n",
    "        self.hop_length = hop_length\n",
    "        self.context_frames = context_frames  # ±frames around each tick\n",
    "    \n",
    "    def extract(self, audio_path, tick_times):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            audio_path: path to .ogg/.egg file\n",
    "            tick_times: array of tick timestamps in seconds [T]\n",
    "        \n",
    "        Returns:\n",
    "            features: [T, D_audio] where D_audio = n_mels * (2*context_frames + 1)\n",
    "        \"\"\"\n",
    "        # TODO: Load audio\n",
    "        y, sr = librosa.load(audio_path, sr=self.sr)\n",
    "        \n",
    "        # TODO: Compute mel spectrogram\n",
    "        mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=self.n_mels, hop_length=self.hop_length)\n",
    "        mel_db = librosa.power_to_db(mel, ref=np.max)\n",
    "        \n",
    "        # TODO: Compute onsets\n",
    "        onset_env = librosa.onset.onset_strength(y=y, sr=sr, hop_length=self.hop_length)\n",
    "        \n",
    "        # TODO: For each tick, extract context window\n",
    "        # Convert tick time to mel frame index\n",
    "        # Stack mel[:, frame-context:frame+context+1]\n",
    "        \n",
    "        features = []  # [T, n_mels * (2*context + 1)]\n",
    "        # TODO: Implement extraction\n",
    "        \n",
    "        return np.array(features)\n",
    "\n",
    "# TODO: Event tokenizer\n",
    "class EventTokenizer:\n",
    "    \"\"\"\n",
    "    Converts canonical events to discrete tokens\n",
    "    \n",
    "    Token vocabulary (~406 tokens):\n",
    "    - BOS, EOS, PAD (3)\n",
    "    - TIME_SHIFT_1 through TIME_SHIFT_64 (64)\n",
    "    - NOTE_{lane}_{row}_{color}_{dir} (4*3*2*9 = 216)\n",
    "    - BOMB_{lane}_{row} (4*3 = 12)\n",
    "    - OBST_WALL_{lane}_{width}_{durbin} (4*4*7 = 112)\n",
    "    \"\"\"\n",
    "    def __init__(self):\n",
    "        self.vocab = self._build_vocab()\n",
    "        self.vocab_size = len(self.vocab)\n",
    "        self.token_to_id = {t: i for i, t in enumerate(self.vocab)}\n",
    "        self.id_to_token = {i: t for t, i in self.token_to_id.items()}\n",
    "    \n",
    "    def _build_vocab(self):\n",
    "        vocab = ['BOS', 'EOS', 'PAD']\n",
    "        \n",
    "        # TIME_SHIFT tokens\n",
    "        for k in range(1, 65):\n",
    "            vocab.append(f'TIME_SHIFT_{k}')\n",
    "        \n",
    "        # NOTE tokens: NOTE_{lane}_{row}_{color}_{dir}\n",
    "        for lane in range(4):\n",
    "            for row in range(3):\n",
    "                for color in [0, 1]:  # 0=red, 1=blue\n",
    "                    for direction in range(9):  # 0-8\n",
    "                        vocab.append(f'NOTE_{lane}_{row}_{color}_{direction}')\n",
    "        \n",
    "        # BOMB tokens\n",
    "        for lane in range(4):\n",
    "            for row in range(3):\n",
    "                vocab.append(f'BOMB_{lane}_{row}')\n",
    "        \n",
    "        # OBSTACLE tokens (simplified: walls only, 7 duration bins)\n",
    "        duration_bins = [8, 16, 32, 64, 128, 256, 999]  # Upper bounds\n",
    "        for lane in range(4):\n",
    "            for width in range(1, 5):\n",
    "                for bin_idx, _ in enumerate(duration_bins):\n",
    "                    vocab.append(f'OBST_WALL_{lane}_{width}_{bin_idx}')\n",
    "        \n",
    "        return vocab\n",
    "    \n",
    "    def events_to_tokens(self, events):\n",
    "        \"\"\"\n",
    "        Convert canonical events to token sequence\n",
    "        \n",
    "        Args:\n",
    "            events: List of {t_sec, tick, type, data}\n",
    "        \n",
    "        Returns:\n",
    "            tokens: List of token strings\n",
    "        \"\"\"\n",
    "        tokens = ['BOS']\n",
    "        current_tick = 0\n",
    "        \n",
    "        # Sort events by tick\n",
    "        sorted_events = sorted(events, key=lambda e: e['tick'])\n",
    "        \n",
    "        for event in sorted_events:\n",
    "            # Emit time shifts\n",
    "            tick_delta = event['tick'] - current_tick\n",
    "            while tick_delta > 0:\n",
    "                shift = min(tick_delta, 64)\n",
    "                tokens.append(f'TIME_SHIFT_{shift}')\n",
    "                tick_delta -= shift\n",
    "                current_tick += shift\n",
    "            \n",
    "            # Emit event token\n",
    "            if event['type'] == 'note':\n",
    "                d = event['data']\n",
    "                if d.get('kind') == 'bomb':\n",
    "                    tokens.append(f\"BOMB_{d['lane']}_{d['row']}\")\n",
    "                else:\n",
    "                    tokens.append(f\"NOTE_{d['lane']}_{d['row']}_{d['color']}_{d['cut_dir']}\")\n",
    "            elif event['type'] == 'obstacle':\n",
    "                d = event['data']\n",
    "                dur_bin = self._duration_to_bin(d['duration_ticks'])\n",
    "                tokens.append(f\"OBST_WALL_{d['lane']}_{d['width']}_{dur_bin}\")\n",
    "        \n",
    "        tokens.append('EOS')\n",
    "        return tokens\n",
    "    \n",
    "    def _duration_to_bin(self, duration_ticks):\n",
    "        bins = [8, 16, 32, 64, 128, 256, 999]\n",
    "        for i, upper in enumerate(bins):\n",
    "            if duration_ticks <= upper:\n",
    "                return i\n",
    "        return len(bins) - 1\n",
    "    \n",
    "    def tokens_to_ids(self, tokens):\n",
    "        return [self.token_to_id[t] for t in tokens]\n",
    "    \n",
    "    def ids_to_tokens(self, ids):\n",
    "        return [self.id_to_token[i] for i in ids]\n",
    "\n",
    "# Test\n",
    "if __name__ == \"__main__\":\n",
    "    tokenizer = EventTokenizer()\n",
    "    print(f\"Vocabulary size: {tokenizer.vocab_size}\")\n",
    "    \n",
    "    # Example events\n",
    "    events = [\n",
    "        {\"tick\": 0, \"type\": \"note\", \"data\": {\"lane\": 1, \"row\": 1, \"color\": 0, \"cut_dir\": 0}},\n",
    "        {\"tick\": 16, \"type\": \"note\", \"data\": {\"lane\": 2, \"row\": 1, \"color\": 1, \"cut_dir\": 1}},\n",
    "    ]\n",
    "    \n",
    "    tokens = tokenizer.events_to_tokens(events)\n",
    "    print(f\"Tokens: {tokens}\")\n",
    "    \n",
    "    ids = tokenizer.tokens_to_ids(tokens)\n",
    "    print(f\"Token IDs: {ids}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Week 3: Model Architecture"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import math\n",
    "\n",
    "# TODO: Implement Transformer generator\n",
    "class BeatSaberGenerator(nn.Module):\n",
    "    \"\"\"\n",
    "    Audio → Token sequence generator\n",
    "    \n",
    "    Architecture:\n",
    "    - Audio encoder: Transformer encoder over tick-aligned features\n",
    "    - Token decoder: Transformer decoder (autoregressive)\n",
    "    - Conditioning: Difficulty embedding\n",
    "    \"\"\"\n",
    "    def __init__(self, \n",
    "                 vocab_size=406,\n",
    "                 d_model=512,\n",
    "                 n_heads=8,\n",
    "                 n_encoder_layers=6,\n",
    "                 n_decoder_layers=6,\n",
    "                 d_audio=640,  # 128 mels * 5 context frames\n",
    "                 max_seq_len=4096,\n",
    "                 dropout=0.1):\n",
    "        super().__init__()\n",
    "        \n",
    "        self.d_model = d_model\n",
    "        \n",
    "        # Difficulty embedding (Easy=0, Normal=1, Hard=2, Expert=3, Expert+=4)\n",
    "        self.difficulty_embed = nn.Embedding(5, d_model)\n",
    "        \n",
    "        # Audio encoder\n",
    "        self.audio_proj = nn.Linear(d_audio, d_model)\n",
    "        self.audio_pos_encoding = PositionalEncoding(d_model, max_len=max_seq_len)\n",
    "        encoder_layer = nn.TransformerEncoderLayer(\n",
    "            d_model=d_model, nhead=n_heads, dim_feedforward=d_model*4, dropout=dropout, batch_first=True\n",
    "        )\n",
    "        self.audio_encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_encoder_layers)\n",
    "        \n",
    "        # Token decoder\n",
    "        self.token_embed = nn.Embedding(vocab_size, d_model)\n",
    "        self.token_pos_encoding = PositionalEncoding(d_model, max_len=max_seq_len)\n",
    "        decoder_layer = nn.TransformerDecoderLayer(\n",
    "            d_model=d_model, nhead=n_heads, dim_feedforward=d_model*4, dropout=dropout, batch_first=True\n",
    "        )\n",
    "        self.token_decoder = nn.TransformerDecoder(decoder_layer, num_layers=n_decoder_layers)\n",
    "        \n",
    "        # Output projection\n",
    "        self.output_proj = nn.Linear(d_model, vocab_size)\n",
    "    \n",
    "    def forward(self, audio_features, token_ids, difficulty_level, tgt_mask=None):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            audio_features: [B, T_audio, D_audio]\n",
    "            token_ids: [B, T_tokens] (input sequence)\n",
    "            difficulty_level: [B] (0-4)\n",
    "            tgt_mask: [T_tokens, T_tokens] causal mask\n",
    "        \n",
    "        Returns:\n",
    "            logits: [B, T_tokens, vocab_size]\n",
    "        \"\"\"\n",
    "        # Encode audio\n",
    "        audio_embed = self.audio_proj(audio_features)  # [B, T_audio, d_model]\n",
    "        audio_embed = self.audio_pos_encoding(audio_embed)\n",
    "        \n",
    "        # Add difficulty conditioning (broadcast to all audio frames)\n",
    "        diff_embed = self.difficulty_embed(difficulty_level)  # [B, d_model]\n",
    "        audio_embed = audio_embed + diff_embed.unsqueeze(1)  # Broadcast\n",
    "        \n",
    "        memory = self.audio_encoder(audio_embed)  # [B, T_audio, d_model]\n",
    "        \n",
    "        # Decode tokens\n",
    "        token_embed = self.token_embed(token_ids)  # [B, T_tokens, d_model]\n",
    "        token_embed = self.token_pos_encoding(token_embed)\n",
    "        \n",
    "        if tgt_mask is None:\n",
    "            tgt_mask = self._generate_square_subsequent_mask(token_ids.size(1)).to(token_ids.device)\n",
    "        \n",
    "        decoder_out = self.token_decoder(\n",
    "            tgt=token_embed,\n",
    "            memory=memory,\n",
    "            tgt_mask=tgt_mask\n",
    "        )  # [B, T_tokens, d_model]\n",
    "        \n",
    "        logits = self.output_proj(decoder_out)  # [B, T_tokens, vocab_size]\n",
    "        return logits\n",
    "    \n",
    "    def _generate_square_subsequent_mask(self, sz):\n",
    "        mask = torch.triu(torch.ones(sz, sz), diagonal=1).bool()\n",
    "        return mask\n",
    "\n",
    "class PositionalEncoding(nn.Module):\n",
    "    def __init__(self, d_model, max_len=5000):\n",
    "        super().__init__()\n",
    "        pe = torch.zeros(max_len, d_model)\n",
    "        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)\n",
    "        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))\n",
    "        pe[:, 0::2] = torch.sin(position * div_term)\n",
    "        pe[:, 1::2] = torch.cos(position * div_term)\n",
    "        pe = pe.unsqueeze(0)  # [1, max_len, d_model]\n",
    "        self.register_buffer('pe', pe)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        # x: [B, T, d_model]\n",
    "        return x + self.pe[:, :x.size(1), :]\n",
    "\n",
    "# Test model\n",
    "if __name__ == \"__main__\":\n",
    "    model = BeatSaberGenerator()\n",
    "    \n",
    "    # Dummy inputs\n",
    "    B, T_audio, T_tokens = 2, 100, 50\n",
    "    audio_features = torch.randn(B, T_audio, 640)\n",
    "    token_ids = torch.randint(0, 406, (B, T_tokens))\n",
    "    difficulty = torch.tensor([3, 4])  # Expert, Expert+\n",
    "    \n",
    "    logits = model(audio_features, token_ids, difficulty)\n",
    "    print(f\"Output shape: {logits.shape}\")  # [2, 50, 406]\n",
    "    print(f\"Model parameters: {sum(p.numel() for p in model.parameters()) / 1e6:.1f}M\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Week 4: Training Loop & Constraint Validation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "from torch.utils.data import Dataset, DataLoader\n",
    "import torch.optim as optim\n",
    "\n",
    "# TODO: Dataset class\n",
    "class BeatSaberDataset(Dataset):\n",
    "    \"\"\"\n",
    "    Loads preprocessed training data\n",
    "    \n",
    "    Each sample:\n",
    "    - audio_features: [T_audio, D_audio]\n",
    "    - token_ids: [T_tokens]\n",
    "    - difficulty: int (0-4)\n",
    "    - metadata: dict (for debugging)\n",
    "    \"\"\"\n",
    "    def __init__(self, data_dir, split='train'):\n",
    "        # TODO: Load preprocessed .pt files\n",
    "        self.samples = []  # List of preprocessed samples\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.samples)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        # TODO: Return sample\n",
    "        return {\n",
    "            'audio_features': torch.tensor([]),  # [T_audio, D_audio]\n",
    "            'token_ids': torch.tensor([]),  # [T_tokens]\n",
    "            'difficulty': 0\n",
    "        }\n",
    "\n",
    "# TODO: Training function\n",
    "def train_epoch(model, dataloader, optimizer, device, tokenizer):\n",
    "    model.train()\n",
    "    total_loss = 0\n",
    "    \n",
    "    for batch in dataloader:\n",
    "        audio_features = batch['audio_features'].to(device)\n",
    "        token_ids = batch['token_ids'].to(device)\n",
    "        difficulty = batch['difficulty'].to(device)\n",
    "        \n",
    "        # Teacher forcing: input = tokens[:-1], target = tokens[1:]\n",
    "        input_ids = token_ids[:, :-1]\n",
    "        target_ids = token_ids[:, 1:]\n",
    "        \n",
    "        # Forward pass\n",
    "        logits = model(audio_features, input_ids, difficulty)\n",
    "        \n",
    "        # Loss (cross-entropy, ignore PAD tokens)\n",
    "        loss = F.cross_entropy(\n",
    "            logits.reshape(-1, logits.size(-1)),\n",
    "            target_ids.reshape(-1),\n",
    "            ignore_index=tokenizer.token_to_id['PAD']\n",
    "        )\n",
    "        \n",
    "        # Backward\n",
    "        optimizer.zero_grad()\n",
    "        loss.backward()\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
    "        optimizer.step()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "    \n",
    "    return total_loss / len(dataloader)\n",
    "\n",
    "# TODO: Constraint validator\n",
    "class ConstraintValidator:\n",
    "    \"\"\"\n",
    "    Validates generated maps against playability constraints\n",
    "    \n",
    "    Hard constraints:\n",
    "    - Max 2 notes per hand per tick\n",
    "    - No impossible hand spreads (e.g., red lanes 0+3 simultaneously)\n",
    "    - No obstacles blocking required notes\n",
    "    - Cut direction consistency (no 180° flips at high speed)\n",
    "    \"\"\"\n",
    "    def __init__(self, max_notes_per_hand=2):\n",
    "        self.max_notes_per_hand = max_notes_per_hand\n",
    "    \n",
    "    def validate(self, events):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            events: List of canonical events\n",
    "        \n",
    "        Returns:\n",
    "            is_valid: bool\n",
    "            violations: List of violation descriptions\n",
    "        \"\"\"\n",
    "        violations = []\n",
    "        \n",
    "        # Group events by tick\n",
    "        tick_groups = {}\n",
    "        for event in events:\n",
    "            tick = event['tick']\n",
    "            if tick not in tick_groups:\n",
    "                tick_groups[tick] = []\n",
    "            tick_groups[tick].append(event)\n",
    "        \n",
    "        # Check each tick\n",
    "        for tick, tick_events in tick_groups.items():\n",
    "            # Count notes per hand\n",
    "            red_notes = [e for e in tick_events if e['type'] == 'note' and e['data'].get('color') == 0]\n",
    "            blue_notes = [e for e in tick_events if e['type'] == 'note' and e['data'].get('color') == 1]\n",
    "            \n",
    "            if len(red_notes) > self.max_notes_per_hand:\n",
    "                violations.append(f\"Tick {tick}: {len(red_notes)} red notes (max {self.max_notes_per_hand})\")\n",
    "            if len(blue_notes) > self.max_notes_per_hand:\n",
    "                violations.append(f\"Tick {tick}: {len(blue_notes)} blue notes (max {self.max_notes_per_hand})\")\n",
    "            \n",
    "            # TODO: Add more constraint checks\n",
    "            # - Lane spread check\n",
    "            # - Obstacle-note collision\n",
    "            # - Cut direction consistency\n",
    "        \n",
    "        return len(violations) == 0, violations\n",
    "    \n",
    "    def fix(self, events):\n",
    "        \"\"\"\n",
    "        Attempt to fix violations by removing/modifying events\n",
    "        \n",
    "        Returns:\n",
    "            fixed_events: List of canonical events\n",
    "        \"\"\"\n",
    "        # TODO: Implement simple fixes\n",
    "        # - Remove excess notes (keep first N per hand)\n",
    "        # - Adjust obstacle timing\n",
    "        return events\n",
    "\n",
    "# Training script\n",
    "if __name__ == \"__main__\":\n",
    "    # Setup\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    model = BeatSaberGenerator().to(device)\n",
    "    tokenizer = EventTokenizer()\n",
    "    \n",
    "    # Data\n",
    "    train_dataset = BeatSaberDataset('data/processed', split='train')\n",
    "    train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)\n",
    "    \n",
    "    # Optimizer\n",
    "    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=0.01)\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50)\n",
    "    \n",
    "    # Train\n",
    "    for epoch in range(50):\n",
    "        loss = train_epoch(model, train_loader, optimizer, device, tokenizer)\n",
    "        scheduler.step()\n",
    "        \n",
    "        print(f\"Epoch {epoch+1}/50 | Loss: {loss:.4f}\")\n",
    "        \n",
    "        # Save checkpoint\n",
    "        if (epoch + 1) % 10 == 0:\n",
    "            torch.save(model.state_dict(), f'checkpoints/model_epoch_{epoch+1}.pt')\n",
    "    \n",
    "    print(\"Phase 1 training complete!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## 4. Phase 2: Quality Expansion & Scorer (Weeks 5-8) {#phase2}\n",
    "\n",
    "### Goals\n",
    "- Expand dataset with tiered vote thresholds\n",
    "- Train quality scorer (pairwise ranking)\n",
    "- Implement candidate generation + reranking\n",
    "- Significant quality improvement\n",
    "\n",
    "### Week 5-6: Quality Scorer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# TODO: Quality scorer network\n",
    "class QualityScorer(nn.Module):\n",
    "    \"\"\"\n",
    "    Predicts map quality score\n",
    "    \n",
    "    Inputs:\n",
    "    - Audio features [T, D_audio]\n",
    "    - Map representation [T, D_map] (per-tick note/obstacle counts)\n",
    "    \n",
    "    Output:\n",
    "    - Quality score (scalar)\n",
    "    \n",
    "    Training:\n",
    "    - Pairwise ranking: L = -log(sigmoid(score_A - score_B))\n",
    "      where map A is preferred over map B\n",
    "    \"\"\"\n",
    "    def __init__(self, d_audio=640, d_map=32, d_model=256, n_layers=4):\n",
    "        super().__init__()\n",
    "        \n",
    "        # Project inputs\n",
    "        self.audio_proj = nn.Linear(d_audio, d_model)\n",
    "        self.map_proj = nn.Linear(d_map, d_model)\n",
    "        \n",
    "        # Transformer encoder\n",
    "        encoder_layer = nn.TransformerEncoderLayer(\n",
    "            d_model=d_model, nhead=8, dim_feedforward=d_model*4, batch_first=True\n",
    "        )\n",
    "        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)\n",
    "        \n",
    "        # Pooling + scoring\n",
    "        self.score_head = nn.Sequential(\n",
    "            nn.Linear(d_model, d_model),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(d_model, 1)\n",
    "        )\n",
    "    \n",
    "    def forward(self, audio_features, map_features):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            audio_features: [B, T, D_audio]\n",
    "            map_features: [B, T, D_map]\n",
    "        \n",
    "        Returns:\n",
    "            scores: [B] scalar quality scores\n",
    "        \"\"\"\n",
    "        # Combine audio + map\n",
    "        audio_embed = self.audio_proj(audio_features)\n",
    "        map_embed = self.map_proj(map_features)\n",
    "        combined = audio_embed + map_embed  # [B, T, d_model]\n",
    "        \n",
    "        # Encode\n",
    "        encoded = self.encoder(combined)  # [B, T, d_model]\n",
    "        \n",
    "        # Pool (mean over time)\n",
    "        pooled = encoded.mean(dim=1)  # [B, d_model]\n",
    "        \n",
    "        # Score\n",
    "        scores = self.score_head(pooled).squeeze(-1)  # [B]\n",
    "        return scores\n",
    "\n",
    "def train_scorer_epoch(scorer, dataloader, optimizer, device):\n",
    "    \"\"\"\n",
    "    Train scorer with pairwise ranking loss\n",
    "    \n",
    "    Dataloader yields:\n",
    "    - audio_A, map_A (preferred)\n",
    "    - audio_B, map_B (less preferred)\n",
    "    \"\"\"\n",
    "    scorer.train()\n",
    "    total_loss = 0\n",
    "    \n",
    "    for batch in dataloader:\n",
    "        audio_A = batch['audio_A'].to(device)\n",
    "        map_A = batch['map_A'].to(device)\n",
    "        audio_B = batch['audio_B'].to(device)\n",
    "        map_B = batch['map_B'].to(device)\n",
    "        \n",
    "        # Score both\n",
    "        score_A = scorer(audio_A, map_A)\n",
    "        score_B = scorer(audio_B, map_B)\n",
    "        \n",
    "        # Pairwise ranking loss: prefer A > B\n",
    "        loss = -torch.log(torch.sigmoid(score_A - score_B)).mean()\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "    \n",
    "    return total_loss / len(dataloader)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Week 7-8: Candidate Generation & Reranking"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# TODO: Generation pipeline with reranking\n",
    "def generate_best_map(generator, scorer, audio_path, difficulty, \n",
    "                      n_candidates=16, device='cuda'):\n",
    "    \"\"\"\n",
    "    Generate multiple candidates and select the best\n",
    "    \n",
    "    Args:\n",
    "        generator: Trained BeatSaberGenerator\n",
    "        scorer: Trained QualityScorer\n",
    "        audio_path: Path to .ogg/.egg file\n",
    "        difficulty: int (0-4)\n",
    "        n_candidates: Number of candidates to generate\n",
    "    \n",
    "    Returns:\n",
    "        best_map: Canonical events for best map\n",
    "        score: Quality score\n",
    "    \"\"\"\n",
    "    generator.eval()\n",
    "    scorer.eval()\n",
    "    \n",
    "    # Extract audio features\n",
    "    extractor = AudioFeatureExtractor()\n",
    "    # TODO: Get tick times from BPM\n",
    "    tick_times = []  # Placeholder\n",
    "    audio_features = extractor.extract(audio_path, tick_times)\n",
    "    audio_tensor = torch.tensor(audio_features).unsqueeze(0).to(device)\n",
    "    \n",
    "    candidates = []\n",
    "    validator = ConstraintValidator()\n",
    "    tokenizer = EventTokenizer()\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for _ in range(n_candidates):\n",
    "            # Generate with sampling (temperature=0.8 for diversity)\n",
    "            token_ids = generate_sequence(\n",
    "                generator, \n",
    "                audio_tensor, \n",
    "                difficulty, \n",
    "                max_len=2048, \n",
    "                temperature=0.8,\n",
    "                tokenizer=tokenizer\n",
    "            )\n",
    "            \n",
    "            # Convert to events\n",
    "            tokens = tokenizer.ids_to_tokens(token_ids)\n",
    "            events = tokens_to_events(tokens)  # TODO: Implement\n",
    "            \n",
    "            # Validate\n",
    "            is_valid, violations = validator.validate(events)\n",
    "            if not is_valid:\n",
    "                events = validator.fix(events)\n",
    "            \n",
    "            # Convert to map features for scoring\n",
    "            map_features = events_to_map_features(events, len(tick_times))  # TODO: Implement\n",
    "            map_tensor = torch.tensor(map_features).unsqueeze(0).to(device)\n",
    "            \n",
    "            # Score\n",
    "            score = scorer(audio_tensor, map_tensor).item()\n",
    "            \n",
    "            candidates.append((events, score))\n",
    "    \n",
    "    # Select best\n",
    "    best_map, best_score = max(candidates, key=lambda x: x[1])\n",
    "    \n",
    "    print(f\"Generated {n_candidates} candidates, best score: {best_score:.3f}\")\n",
    "    return best_map, best_score\n",
    "\n",
    "def generate_sequence(model, audio_features, difficulty, max_len=2048, \n",
    "                     temperature=1.0, tokenizer=None):\n",
    "    \"\"\"\n",
    "    Autoregressive generation with sampling\n",
    "    \n",
    "    Returns:\n",
    "        token_ids: List of generated token IDs\n",
    "    \"\"\"\n",
    "    model.eval()\n",
    "    device = audio_features.device\n",
    "    \n",
    "    # Start with BOS\n",
    "    bos_id = tokenizer.token_to_id['BOS']\n",
    "    eos_id = tokenizer.token_to_id['EOS']\n",
    "    \n",
    "    generated = [bos_id]\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for _ in range(max_len):\n",
    "            # Current sequence\n",
    "            token_tensor = torch.tensor([generated]).to(device)\n",
    "            diff_tensor = torch.tensor([difficulty]).to(device)\n",
    "            \n",
    "            # Forward pass\n",
    "            logits = model(audio_features, token_tensor, diff_tensor)\n",
    "            \n",
    "            # Sample next token (with temperature)\n",
    "            next_logits = logits[0, -1, :] / temperature\n",
    "            probs = F.softmax(next_logits, dim=-1)\n",
    "            next_token = torch.multinomial(probs, num_samples=1).item()\n",
    "            \n",
    "            generated.append(next_token)\n",
    "            \n",
    "            # Stop at EOS\n",
    "            if next_token == eos_id:\n",
    "                break\n",
    "    \n",
    "    return generated"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## 5. Phase 3: Advanced Features (Weeks 9-12) {#phase3}\n",
    "\n",
    "### Goals\n",
    "- Add BPM change support\n",
    "- Add style conditioning (optional)\n",
    "- Add basic lighting events\n",
    "- Polish constraint validation\n",
    "- Build CLI tool\n",
    "\n",
    "### Features to Add\n",
    "\n",
    "**BPM Changes:**\n",
    "- Parse BPM events from Info.dat\n",
    "- Piecewise beat→seconds conversion\n",
    "- Handle in feature extraction\n",
    "\n",
    "**Style Conditioning:**\n",
    "- Cluster mappers by style (optional)\n",
    "- Add style embedding to model\n",
    "- Condition generation on style\n",
    "\n",
    "**Lighting:**\n",
    "- Add basic light tokens (ON/OFF, colors)\n",
    "- Sync to beat/onsets\n",
    "- Train on real lighting patterns\n",
    "\n",
    "**CLI Tool:**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# TODO: Command-line interface\n",
    "\"\"\"\n",
    "Usage:\n",
    "    python generate.py --audio song.ogg --difficulty Expert+ --output output/\n",
    "    \n",
    "Options:\n",
    "    --audio PATH          Input audio file (.ogg/.egg)\n",
    "    --difficulty LEVEL    Easy|Normal|Hard|Expert|Expert+\n",
    "    --output DIR          Output directory for .dat files\n",
    "    --n-candidates N      Number of candidates to generate (default: 16)\n",
    "    --model PATH          Path to trained model checkpoint\n",
    "    --scorer PATH         Path to trained scorer checkpoint\n",
    "    --add-to-library      Automatically add to Beat Saber library\n",
    "\"\"\"\n",
    "\n",
    "import argparse\n",
    "import os\n",
    "import shutil\n",
    "\n",
    "def main():\n",
    "    parser = argparse.ArgumentParser(description='Generate Beat Saber level from audio')\n",
    "    parser.add_argument('--audio', required=True, help='Input audio file')\n",
    "    parser.add_argument('--difficulty', required=True, \n",
    "                       choices=['Easy', 'Normal', 'Hard', 'Expert', 'Expert+'])\n",
    "    parser.add_argument('--output', required=True, help='Output directory')\n",
    "    parser.add_argument('--n-candidates', type=int, default=16)\n",
    "    parser.add_argument('--model', default='checkpoints/best_generator.pt')\n",
    "    parser.add_argument('--scorer', default='checkpoints/best_scorer.pt')\n",
    "    parser.add_argument('--add-to-library', action='store_true')\n",
    "    \n",
    "    args = parser.parse_args()\n",
    "    \n",
    "    # Load models\n",
    "    print(\"Loading models...\")\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    generator = BeatSaberGenerator().to(device)\n",
    "    generator.load_state_dict(torch.load(args.model))\n",
    "    \n",
    "    scorer = QualityScorer().to(device)\n",
    "    scorer.load_state_dict(torch.load(args.scorer))\n",
    "    \n",
    "    # Map difficulty\n",
    "    diff_map = {'Easy': 0, 'Normal': 1, 'Hard': 2, 'Expert': 3, 'Expert+': 4}\n",
    "    difficulty = diff_map[args.difficulty]\n",
    "    \n",
    "    # Generate\n",
    "    print(f\"Generating {args.difficulty} level...\")\n",
    "    best_map, score = generate_best_map(\n",
    "        generator, scorer, args.audio, difficulty, \n",
    "        n_candidates=args.n_candidates, device=device\n",
    "    )\n",
    "    \n",
    "    # Write output files\n",
    "    os.makedirs(args.output, exist_ok=True)\n",
    "    \n",
    "    # TODO: Convert events back to .dat format\n",
    "    # write_info_dat(args.output, metadata)\n",
    "    # write_difficulty_dat(args.output, best_map, args.difficulty)\n",
    "    \n",
    "    # Copy audio\n",
    "    shutil.copy(args.audio, os.path.join(args.output, 'song.egg'))\n",
    "    \n",
    "    print(f\"Generated level (quality score: {score:.3f})\")\n",
    "    print(f\"Output: {args.output}\")\n",
    "    \n",
    "    # Add to library\n",
    "    if args.add_to_library:\n",
    "        library_path = os.path.expanduser('~/Beat Saber/CustomLevels')\n",
    "        if os.path.exists(library_path):\n",
    "            level_name = os.path.basename(args.output)\n",
    "            dest = os.path.join(library_path, level_name)\n",
    "            shutil.copytree(args.output, dest)\n",
    "            print(f\"Added to library: {dest}\")\n",
    "        else:\n",
    "            print(f\"Warning: Library not found at {library_path}\")\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## 6. Implementation Checklist {#checklist}\n",
    "\n",
    "### Phase 1 (Weeks 1-4)\n",
    "\n",
    "**Week 1:**\n",
    "- [ ] Set up project structure\n",
    "- [ ] Implement BeatSaver API client\n",
    "- [ ] Download test dataset (1000 maps)\n",
    "- [ ] Implement v2 parser\n",
    "- [ ] Implement canonical schema\n",
    "- [ ] Test parsing on 100 maps\n",
    "\n",
    "**Week 2:**\n",
    "- [ ] Implement AudioFeatureExtractor\n",
    "- [ ] Implement EventTokenizer\n",
    "- [ ] Preprocess 1000 maps to .pt files\n",
    "- [ ] Verify feature quality (visualize spectrograms)\n",
    "- [ ] Verify tokenization (reconstruct events)\n",
    "\n",
    "**Week 3:**\n",
    "- [ ] Implement BeatSaberGenerator model\n",
    "- [ ] Test forward/backward pass\n",
    "- [ ] Implement Dataset + DataLoader\n",
    "- [ ] Test overfitting on 10 samples (sanity check)\n",
    "\n",
    "**Week 4:**\n",
    "- [ ] Implement training loop\n",
    "- [ ] Train on full dataset (50 epochs)\n",
    "- [ ] Implement ConstraintValidator\n",
    "- [ ] Generate first playable map\n",
    "- [ ] Playtest and document issues\n",
    "\n",
    "### Phase 2 (Weeks 5-8)\n",
    "\n",
    "**Week 5:**\n",
    "- [ ] Download expanded dataset (20k+ maps)\n",
    "- [ ] Implement tiered filtering\n",
    "- [ ] Preprocess new data\n",
    "\n",
    "**Week 6:**\n",
    "- [ ] Implement QualityScorer\n",
    "- [ ] Create pairwise training pairs\n",
    "- [ ] Train scorer\n",
    "\n",
    "**Week 7:**\n",
    "- [ ] Implement candidate generation\n",
    "- [ ] Implement reranking pipeline\n",
    "- [ ] Test on 10 songs\n",
    "\n",
    "**Week 8:**\n",
    "- [ ] Tune hyperparameters (n_candidates, temperature)\n",
    "- [ ] Large-scale playtest (20+ maps)\n",
    "- [ ] Collect feedback\n",
    "- [ ] Iterate on constraints\n",
    "\n",
    "### Phase 3 (Weeks 9-12)\n",
    "\n",
    "**Week 9:**\n",
    "- [ ] Add BPM change parsing\n",
    "- [ ] Retrain on variable-BPM maps\n",
    "\n",
    "**Week 10:**\n",
    "- [ ] Add lighting tokens (if desired)\n",
    "- [ ] Train with lighting data\n",
    "\n",
    "**Week 11:**\n",
    "- [ ] Build CLI tool\n",
    "- [ ] Add auto-library feature\n",
    "- [ ] Write user documentation\n",
    "\n",
    "**Week 12:**\n",
    "- [ ] Final playtesting\n",
    "- [ ] Gather community feedback\n",
    "- [ ] Polish and release\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Evaluation Framework {#evaluation}\n",
    "\n",
    "### Automated Metrics\n",
    "\n",
    "Track these during training and generation:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# TODO: Evaluation metrics\n",
    "class EvaluationMetrics:\n",
    "    \"\"\"\n",
    "    Automated quality metrics for generated maps\n",
    "    \"\"\"\n",
    "    @staticmethod\n",
    "    def constraint_violation_rate(events):\n",
    "        \"\"\"Percentage of maps that violate hard constraints\"\"\"\n",
    "        validator = ConstraintValidator()\n",
    "        is_valid, _ = validator.validate(events)\n",
    "        return 0.0 if is_valid else 1.0\n",
    "    \n",
    "    @staticmethod\n",
    "    def beat_alignment_score(events, beat_times):\n",
    "        \"\"\"\n",
    "        How well notes align to beats/downbeats\n",
    "        \n",
    "        Returns: 0-1 score (1 = perfect alignment)\n",
    "        \"\"\"\n",
    "        note_events = [e for e in events if e['type'] == 'note']\n",
    "        if len(note_events) == 0:\n",
    "            return 0.0\n",
    "        \n",
    "        aligned_count = 0\n",
    "        threshold = 0.05  # 50ms tolerance\n",
    "        \n",
    "        for note in note_events:\n",
    "            t = note['t_sec']\n",
    "            # Find nearest beat\n",
    "            distances = [abs(t - bt) for bt in beat_times]\n",
    "            if min(distances) < threshold:\n",
    "                aligned_count += 1\n",
    "        \n",
    "        return aligned_count / len(note_events)\n",
    "    \n",
    "    @staticmethod\n",
    "    def distribution_match(generated_events, real_events):\n",
    "        \"\"\"\n",
    "        Compare generated map statistics to real maps\n",
    "        \n",
    "        Metrics:\n",
    "        - Notes per second\n",
    "        - Chord rate (multi-note ticks)\n",
    "        - Obstacle rate\n",
    "        - Lane usage distribution\n",
    "        \"\"\"\n",
    "        # TODO: Compute statistics\n",
    "        gen_stats = compute_stats(generated_events)\n",
    "        real_stats = compute_stats(real_events)\n",
    "        \n",
    "        # Compare with some distance metric\n",
    "        # Return similarity score 0-1\n",
    "        return 0.0\n",
    "    \n",
    "    @staticmethod\n",
    "    def diversity_score(candidates):\n",
    "        \"\"\"\n",
    "        How diverse are N generated candidates?\n",
    "        \n",
    "        Low diversity = mode collapse\n",
    "        \"\"\"\n",
    "        # TODO: Compute pairwise differences between candidates\n",
    "        # E.g., edit distance between token sequences\n",
    "        return 0.0\n",
    "\n",
    "def compute_stats(events):\n",
    "    \"\"\"Helper to compute map statistics\"\"\"\n",
    "    notes = [e for e in events if e['type'] == 'note']\n",
    "    obstacles = [e for e in events if e['type'] == 'obstacle']\n",
    "    \n",
    "    if len(events) == 0:\n",
    "        return {}\n",
    "    \n",
    "    duration = events[-1]['t_sec']\n",
    "    \n",
    "    return {\n",
    "        'notes_per_sec': len(notes) / duration if duration > 0 else 0,\n",
    "        'obstacles_per_sec': len(obstacles) / duration if duration > 0 else 0,\n",
    "        # TODO: Add more stats\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Human Evaluation Protocol\n",
    "\n",
    "**Testing procedure:**\n",
    "\n",
    "1. **Generate test set:** 20 maps across different songs/difficulties\n",
    "2. **Blind A/B testing:** Mix with 20 real high-quality maps\n",
    "3. **Playtest criteria:**\n",
    "   - Flow (does it feel natural?)\n",
    "   - Fun (is it enjoyable?)\n",
    "   - Readability (can you react in time?)\n",
    "   - Musicality (does it match the song?)\n",
    "   - Overall quality (1-5 scale)\n",
    "\n",
    "4. **Success target:** 80%+ of testers rate generated maps ≥4/5\n",
    "\n",
    "**Feedback collection:**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# TODO: Feedback collection template\n",
    "\"\"\"\n",
    "Map Evaluation Form\n",
    "==================\n",
    "\n",
    "Map ID: _______________\n",
    "Your skill level: Easy / Normal / Hard / Expert / Expert+\n",
    "\n",
    "Ratings (1-5 scale):\n",
    "- Flow: ___ (Does it feel smooth and natural?)\n",
    "- Fun: ___ (Did you enjoy playing it?)\n",
    "- Readability: ___ (Could you react to the patterns?)\n",
    "- Musicality: ___ (Does it match the song well?)\n",
    "- Overall: ___ (Would you recommend this map?)\n",
    "\n",
    "Comments:\n",
    "- What worked well?\n",
    "- What felt off or frustrating?\n",
    "- Specific moments (timestamp) that were great/bad?\n",
    "\n",
    "Would you guess this map was:\n",
    "[ ] Made by a human mapper\n",
    "[ ] Made by AI\n",
    "[ ] Not sure\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Next Steps\n",
    "\n",
    "### Getting Started (Now)\n",
    "\n",
    "1. **Set up environment:**\n",
    "   ```bash\n",
    "   conda create -n beatsaber python=3.10\n",
    "   conda activate beatsaber\n",
    "   pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118\n",
    "   pip install librosa madmom numpy pandas tqdm jupyter\n",
    "   ```\n",
    "\n",
    "2. **Create project structure:**\n",
    "   ```\n",
    "   beatsaber-ml/\n",
    "   ├── data/\n",
    "   │   ├── raw/          # Downloaded maps\n",
    "   │   ├── processed/    # Preprocessed .pt files\n",
    "   │   └── metadata.json\n",
    "   ├── src/\n",
    "   │   ├── data/         # Data pipeline\n",
    "   │   ├── models/       # Model architectures\n",
    "   │   ├── training/     # Training loops\n",
    "   │   └── evaluation/   # Metrics\n",
    "   ├── checkpoints/\n",
    "   ├── outputs/\n",
    "   └── notebooks/        # Jupyter notebooks\n",
    "   ```\n",
    "\n",
    "3. **Start with Week 1 tasks** (see checklist above)\n",
    "\n",
    "4. **Implementation approach:**\n",
    "   - Start with the data pipeline components\n",
    "   - Test each component individually before integration\n",
    "   - Iterate on results using training metrics\n",
    "\n",
    "### Resources\n",
    "\n",
    "**Documentation:**\n",
    "- See `data_pipeline_spec.md` for detailed data specs\n",
    "- See `model_architecture_spec.md` for architecture details\n",
    "- See `phase_1_checklist.md` for week-by-week breakdown\n",
    "\n",
    "**Key References:**\n",
    "- BeatSaver API: https://api.beatsaver.com/docs/\n",
    "- Beat Saber format docs: (community wikis)\n",
    "- PyTorch Transformer tutorial: https://pytorch.org/tutorials/\n",
    "\n",
    "---\n",
    "\n",
    "## Success Criteria Summary\n",
    "\n",
    "**Phase 1:**\n",
    "- Generate playable maps (even if rough)\n",
    "- No major constraint violations\n",
    "- Notes generally aligned to beats\n",
    "\n",
    "**Phase 2:**\n",
    "- Significant quality improvement with scorer\n",
    "- Generated maps in top 50% of playtester rankings\n",
    "- Some maps indistinguishable from human-made\n",
    "\n",
    "**Phase 3:**\n",
    "- 80%+ of users rate maps 4/5 or higher\n",
    "- Working CLI tool\n",
    "- Support for most songs (with BPM changes)\n",
    "\n",
    "**Final Goal:**\n",
    "Create a tool that generates Beat Saber levels matching or exceeding the quality of average community-made maps, with the ability to quickly generate fun, playable content for any song.\n",
    "\n",
    "---\n",
    "\n",
    "*Implementation begins with the Data Pipeline phase.*\n",
    "\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}